import type { Metadata } from "next";
import { Inter, Inknut_Antiqua } from "next/font/google";
import "../globals.css"
import { Suspense } from "react";
import NavbarAdmin from "../ui/navbar/navbarAdmin";

const inter = Inter({ subsets: ["latin"] });
const inknut = Inknut_Antiqua({
    subsets: ["latin"],
    weight: "300"
});



export const metadata: Metadata = {
    title: "Dompet Hidayah",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inknut.className} min-h-screen`}>
                <NavbarAdmin />
                <main className="lg:px-24">
                    {children}
                </main>
            </body>
        </html>
    );
}
