import type { Metadata } from "next";
import { Inter, Inknut_Antiqua } from "next/font/google";
import "../globals.css"
import NavbarAdmin from "../ui/navbar/navbarAdmin";
import { createClient } from "../utils/supabase/supabase_server";
import { redirect } from "next/navigation";
import { TableProvider } from "@/context/tablecontext";

const inter = Inter({ subsets: ["latin"] });
const inknut = Inknut_Antiqua({
    subsets: ["latin"],
    weight: "300"
});



export const metadata: Metadata = {
    title: "Dompet Hidayah",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    const supabase = await createClient();

    let admin = null;

    try {
        const { data: { user } } = await supabase.auth.getUser();

        admin = user;

    } catch (error) {
        console.error("Error fetching user data:", error);
        redirect("/error");
    }

    return (
        <html lang="en">
            <body className={`${inknut.className} min-h-screen`}>
                <NavbarAdmin user={admin} />
                <main className="lg:px-24">
                    <TableProvider>
                        {children}
                    </TableProvider>
                </main>
            </body>
        </html>
    );
}
